"""empty message

Revision ID: 28248932da88
Revises: 
Create Date: 2025-10-17 10:40:40.770754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28248932da88'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('curso',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=40), nullable=False),
    sa.Column('descricao', sa.String(length=150), nullable=False),
    sa.Column('data_criacao', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('curso')
    # ### end Alembic commands ###
