"""empty message

Revision ID: 4fe1d164e326
Revises: f1e7a227e554
Create Date: 2025-10-24 13:18:25.281950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fe1d164e326'
down_revision = 'f1e7a227e554'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('api_key', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'api_key')
    # ### end Alembic commands ###
