"""empty message

Revision ID: 988dcecfdb1f
Revises: 7c0c84ff8797
Create Date: 2025-10-24 08:47:18.997295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '988dcecfdb1f'
down_revision = '7c0c84ff8797'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('id_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'id_admin')
    # ### end Alembic commands ###
