"""empty message

Revision ID: f1e7a227e554
Revises: 988dcecfdb1f
Create Date: 2025-10-24 09:39:09.853007

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f1e7a227e554'
down_revision = '988dcecfdb1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.drop_column('usuario', 'id_admin')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('id_admin', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('usuario', 'is_admin')
    # ### end Alembic commands ###
